version: "3.3"

services:
  manager:
    container_name: manager
    image: crackhash-manager:latest
    ports:
      - "8080:8080"
    environment:
      hashcracker.worker-address : http://worker:8081
  worker:
    container_name: worker
    image: crackhash-worker:latest
    environment:
      hashcracker.manager-address : http://manager:8080
