server:
  port: 8081

spring:
  rabbitmq:
    addresses: 127.0.0.1:5672
    virtual-host: /
    username: guest
    password: guest
    listener:
      simple:
        max-concurrency: 1
        concurrency: 1
        acknowledge-mode: manual
        default-requeue-rejected: false
        prefetch: 1
